export const servicesList = {
  elite: [
    'Basic Partition Demolition and Assembly',
    'Wall Leveling and Simple Finishing',
    'Corner Alignment Approx. 90 Degrees',
    'Standard Electrical Works',
    'Basic Low-Voltage Wiring (Internet, TV Antenna)',
    'Simple Plumbing Installation',
    'Basic Waterproofing in Wet Areas',
    'Floor Screed (Up to 8 cm)',
    'Wall Prep for Wallpaper or Paint',
    'Wallpaper Hanging',
    'Laminate Flooring on Basic Underlay',
    'Tile Installation in Bathrooms (Up to 3 m²)',
    'PVC Skirting Board Installation',
    'Simple Ceiling Installation',
    'Door Installation',
    'Bathtub or Shower Setup',
    'Sink Mounting',
    'Basic Access Panel Installation',
    'Drywall Ceiling Assembly',
    'Basic Cleanup After Work',
  ],

  vip: [
    'Demolition and Construction of Interior Partitions',
    'Wall Leveling with Beacons and Finishing for Wallpaper',
    'Accurate 90-Degree Corner Setup',
    'Electrical Installation Works (Per Project)',
    'Low-Voltage Wiring Installation (Internet, Antenna)',
    'Plumbing and Sewer Installation',
    'Waterproofing of Wet Areas',
    'Floor Screed Pouring (Up to 10 cm, Sand-Concrete / Expanded Clay)',
    'Wall Preparation for Wallpaper',
    'Wallpaper Application',
    'Laminate Flooring Installation on Underlay',
    'Tile Installation on Floors and Walls (Bathrooms, Up to 5 m²)',
    'PVC Floor Baseboards Installation',
    'Stretch Ceiling Installation',
    'Interior Door Installation',
    'Bathtub and Shower Cabin Installation',
    'Sink Installation',
    'Access Panel Installation for Plumbing Stacks',
    'Drywall Ceiling Installation',
    'Cleaning After Renovation',
  ],

  extra: [
    'Comprehensive Demolition and Reconstruction of Interior Partitions',
    'Precision Wall Leveling with Laser Beacons and Premium Finish for Wallpaper',
    'Exact 90-Degree Corner Finishing with Reinforcement',
    'Advanced Electrical Installations and Smart Home System Integration',
    'Installation of High-Speed Fiber Optic and Secure Low-Voltage Wiring',
    'Luxury Plumbing System Setup with Water Saving Technology',
    'State-of-the-Art Waterproofing Solutions for Wet Zones',
    'High-Strength Floor Screed (Up to 15 cm) with Thermal and Sound Insulation',
    'Expert Wall Preparation for Premium Wallpaper and Decorative Finishes',
    'Professional Wallpaper Application with Seamless Results',
    'Installation of Premium Laminate and Hardwood Flooring on Acoustic Underlay',
    'Custom Tile Installation for Floors and Walls (Bathrooms, Kitchens, Up to 10 m²)',
    'Designer PVC and Wooden Floor Skirting Installation',
    'Installation of Designer Stretch and Multi-Level Ceilings',
    'Custom-Fit Installation of Interior Doors with High-Quality Hardware',
    'Installation of Luxury Bathtubs, Shower Cabins, and Spa Equipment',
    'Installation of Designer Bathroom Fixtures and Sinks',
    'Installation of Concealed Access Panels for Plumbing and Electrical Systems',
    'Drywall Ceiling Construction with Integrated Lighting Systems',
    'Thorough Post-Renovation Cleaning and Debris Removal',
  ],
};
